# Site settings
title: Security through Curiosity
header-img: img/home-bg.jpg
email: martin@ingesen.no
description: > # this means to ignore newlines until "baseurl:"
    An IT student studying programming, with a great passion for web security.
baseurl: ""
url: "http://martin.ingesen.no"
twitter_username: Mrtn9
github_username:  MartinIngesen
linkedin_username: http://no.linkedin.com/pub/martin-ingesen/75/856/681/
pgp_key: http://pgp.circl.lu/pks/lookup?op=get&search=0xD78FBD59CD638BB3

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: ["jekyll-paginate"]
