# Site settings
title: Martin Ingesen
email: martin@ingesen.no
description: > # this means to ignore newlines until "baseurl:"
  A IT student studying programming, with a passion for web security.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martin.ingesen.no" # the base hostname & protocol for your site
pgp_key: "http://pgp.circl.lu/pks/lookup?op=get&search=0xD78FBD59CD638BB3"
twitter_username: mrtn9
github_username:  MartinIngesen
linkedIn_url: "http://no.linkedin.com/pub/martin-ingesen/75/856/681/"

# Build settings
markdown: kramdown
